<?php
$strategy_short = array(
  'Money out of Politics',
  'Voting Rights',
  'Advocate & Educate',
  'Dig into Data',
  'Take Legal Action',
  'Activate Citizens',
  'Fund the Movement',
  '(PAC) Political Action',
  'State & Regional',
  'Volunteers',
  'Money out of Politics',
  'Voting Rights',
  'Advocate & Educate',
  'Dig into Data',
  'Take Legal Action',
  'Activate Citizens',
  'Fund the Movement',
  '(PAC) Political Action',
  'State & Regional',
  'Volunteers'
);
$strategy_list = array(
  'Get Money out of Politics',
  'Guarantee Voting Rights',
  'Advocate and Educate',
  'Dig into Data',
  'Take Legal Action',
  'Activate Citizens',
  'Fund the Movement',
  'Political Action Committee',
  'state',
  'volunteers',
  'Get Money out of Politics',
  'Guarantee Voting Rights',
  'Advocate and Educate',
  'Dig into Data',
  'Take Legal Action',
  'Activate Citizens',
  'Fund the Movement',
  'Political Action Committee',
  'state',
  'volunteers'
);
$strategy_class = array(
  'koi-po',
  'koi-po',
  'koi-po-1',
  'koi-po-1',
  'koi-po-1',
  'koi-po-1',
  'koi-po-1',
  'koi-po-1',
  'koi-po-2',
  'koi-po-3',
  'koi-po',
  'koi-po',
  'koi-po-1',
  'koi-po-1',
  'koi-po-1',
  'koi-po-1',
  'koi-po-1',
  'koi-po-1',
  'koi-po-2',
  'koi-po-3'
);
?>